version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_pass
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: backend
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./backend/src:/app/src
    command: ["npm", "run", "dev"]
    depends_on:
      - database

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - "5173:5173"
    expose:
      - "5173"
    volumes:
      - ./frontend/src:/app/src

volumes:
  postgres-data:
