openapi: 3.0.3
info:
  title: Notes API
  version: 1.0.0
  description: A simple API to manage notes using Express and Postgres

servers:
  - url: http://localhost:3000

paths:
  /api/v1/notes:
    get:
      summary: Get all notes
      responses:
        "200":
          description: List of notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Note"

    post:
      summary: Create a new note
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewNote"
      responses:
        "201":
          description: Note created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"

  /api/v1/notes/{id}:
    get:
      summary: Get a note by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Note found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
        "404":
          description: Note not found

    put:
      summary: Update a note by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewNote"
      responses:
        "200":
          description: Note updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
        "404":
          description: Note not found

    delete:
      summary: Delete a note by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Note deleted successfully
        "404":
          description: Note not found

components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        content:
          type: string
      required:
        - id
        - title
        - content
      example:
        id: "a1b2c3d4-5678-90ab-cdef-1234567890ab"
        title: "Meeting Notes"
        content: "Discuss project timeline and deliverables."

    NewNote:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      required:
        - title
        - content
      example:
        title: "Sprint Planning"
        content: "Prepare JIRA board and finalize backlog before Friday."
